### ISSUE TITLE
Build Errors (TS2304 and TS2688)

### ISSUE THREAD

**Issue by moatazmedhat** [elasticrash/Angular2.leaflet.component#76]
Hi,
Trying to use the Angular2.leaflet.component in my angular2 project, after following the readme file , I get these build errors.

TS2304: Cannot find name 'require'
TS2688	Cannot find type definition file for 'leaflet'.
TS2688	Cannot find type definition file for 'geojson'.
...

Any ideas?

Thank you!

Moataz

**Comment by elasticrash** [comment]
I don't know your configuration so I cant't tell much. Typescript erros are usually advisory and don't always affect the application. I got a working example here https://github.com/elasticrash/Angular.io.MapViewer/tree/developing_npm_module using systemJS. 

Maybe those errors (at least the 2nd one) is because i switched from typings to @types, something you should definately do, when you switch from typescript 1.x to 2.x

**Comment by moatazmedhat** [comment]
Thank you for the example, it helped.
Long story short, I targeted ES5 instead of ES6, and installed the @types you had in the example tsconfig.json

Cheers!

Moataz
